![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on!

In [2]:
import sys
import numpy as np

## Basic Numpy Arrays

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [13]:
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

In [18]:
np.array([1, 2, 3, 4], dtype=np.float)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [19]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [20]:
c = np.array(['a', 'b', 'c'])

In [21]:
c.dtype

dtype('<U1')

In [22]:
d = np.array([{'a': 1}, sys])

In [23]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [24]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [25]:
A.shape

(2, 3)

In [26]:
A.ndim

2

In [27]:
A.size

6

In [28]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [29]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [30]:
B.shape

(2, 2, 3)

In [31]:
B.ndim

3

In [32]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [33]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [34]:
C.dtype

NameError: name 'C' is not defined

In [35]:
C.shape

NameError: name 'C' is not defined

In [36]:
C.size

NameError: name 'C' is not defined

In [37]:
type(C[0])

NameError: name 'C' is not defined

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [38]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [39]:
A[1]

array([4, 5, 6])

In [40]:
A[1][0]

np.int64(4)

In [41]:
# A[d1, d2, d3, d4]

In [42]:
A[1, 0]

np.int64(4)

In [43]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [45]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [46]:
A[:2, 2:]

array([[3],
       [6]])

In [47]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
A[1] = np.array([10, 10, 10])

In [49]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [50]:
A[2] = 99

In [51]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [52]:
a = np.array([1, 2, 3, 4])

In [53]:
a.sum()

np.int64(10)

In [54]:
a.mean()

np.float64(2.5)

In [55]:
a.std()

np.float64(1.118033988749895)

In [56]:
a.var()

np.float64(1.25)

In [57]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [58]:
A.sum()

np.int64(45)

In [59]:
A.mean()

np.float64(5.0)

In [60]:
A.std()

np.float64(2.581988897471611)

In [61]:
A.sum(axis=0)

array([12, 15, 18])

In [62]:
A.sum(axis=1)

array([ 6, 15, 24])

In [63]:
A.mean(axis=0)

array([4., 5., 6.])

In [64]:
A.mean(axis=1)

array([2., 5., 8.])

In [65]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [66]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [67]:
a = np.arange(4)

In [68]:
a

array([0, 1, 2, 3])

In [69]:
a + 10

array([10, 11, 12, 13])

In [70]:
a * 10

array([ 0, 10, 20, 30])

In [71]:
a

array([0, 1, 2, 3])

In [72]:
a += 100

In [73]:
a

array([100, 101, 102, 103])

In [74]:
l = [0, 1, 2, 3]

In [75]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [76]:
a = np.arange(4)

In [77]:
a

array([0, 1, 2, 3])

In [78]:
b = np.array([10, 10, 10, 10])

In [79]:
b

array([10, 10, 10, 10])

In [80]:
a + b

array([10, 11, 12, 13])

In [81]:
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [82]:
a = np.arange(4)

In [83]:
a

array([0, 1, 2, 3])

In [84]:
a[0], a[-1]

(np.int64(0), np.int64(3))

In [85]:
a[[0, -1]]

array([0, 3])

In [86]:
a[[True, False, False, True]]

array([0, 3])

In [87]:
a

array([0, 1, 2, 3])

In [88]:
a >= 2

array([False, False,  True,  True])

In [89]:
a[a >= 2]

array([2, 3])

In [90]:
a.mean()

np.float64(1.5)

In [91]:
a[a > a.mean()]

array([2, 3])

In [92]:
a[~(a > a.mean())]

array([0, 1])

In [93]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [94]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [95]:
A = np.random.randint(100, size=(3, 3))

In [96]:
A

array([[83, 14, 67],
       [92, 18, 12],
       [30, 12, 55]])

In [97]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([83, 67, 18, 30, 55])

In [98]:
A > 30

array([[ True, False,  True],
       [ True, False, False],
       [False, False,  True]])

In [99]:
A[A > 30]

array([83, 67, 92, 55])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [100]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [101]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [102]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [103]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [104]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [105]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [107]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [108]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [109]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [110]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [111]:
np.dtype(float).itemsize

8

### Lists are even larger

In [112]:
# A one-element list
sys.getsizeof([1])

64

In [113]:
# An array of one element in numpy
np.array([1]).nbytes

8

### And performance is also important

In [114]:
l = list(range(100000))

In [115]:
a = np.arange(100000)

In [116]:
%time np.sum(a ** 2)

CPU times: user 386 µs, sys: 1.06 ms, total: 1.44 ms
Wall time: 1.11 ms


np.int64(333328333350000)

In [117]:
%time sum([x ** 2 for x in l])

CPU times: user 8.77 ms, sys: 907 µs, total: 9.67 ms
Wall time: 9.53 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random`

In [118]:
np.random.random(size=2)

array([0.96573397, 0.17048651])

In [119]:
np.random.normal(size=2)

array([-1.04011817, -0.43442034])

In [120]:
np.random.rand(2, 4)

array([[0.27253424, 0.65838688, 0.12237456, 0.61810791],
       [0.47514721, 0.87881317, 0.30507431, 0.42400881]])

---
### `arange`

In [121]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [123]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [124]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [125]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [126]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [127]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [128]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [129]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [130]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [131]:
np.zeros((3, 3), dtype=np.int)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [132]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [133]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [134]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [135]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [136]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [137]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [138]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [139]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [140]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [141]:
"Hello World"[6]

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)