![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

2.0.2


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [38]:
# your code goes here
np.zeros(10, dtype= np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [4]:
# your code goes here
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [7]:
# your code goes here
np.ones([2,2], dtype = np.int64)

array([[1, 1],
       [1, 1]])

In [9]:
np.ones([2,2], dtype=np.int32)

array([[1, 1],
       [1, 1]], dtype=int32)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [10]:
# your code goes here
np.ones([3,2], dtype= np.float64)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.ones([3,2], dtype=np.float32)

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [15]:
# your code goes here
X = np.arange(5)
np.ones_like(X)

array([1, 1, 1, 1, 1])

In [ ]:
X = np.arange(4, dtype=np.int)

np.ones_like(X)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [17]:
# your code goes here
X = np.array([[4,3,2],[9,8,7]])
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [29]:
# your code goes here
np.ones([4,4], dtype= np.int64)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [30]:
np.ones([4,4], dtype=np.int64) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [37]:
# your code goes here
X = np.array([[1,2,3],[4,5,6]], dtype= np.int64)
np.ones_like(X)*7

array([[7, 7, 7],
       [7, 7, 7]])

In [35]:
X = np.array([[2,3], [6,2]], dtype=np.int32)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]], dtype=int32)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [39]:
# your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#np.eye(3)
np.identity(3)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [52]:
# your code goes here
np.random.randint(1,10,3)

array([5, 1, 5])

In [53]:
np.random.randint(10, size=3)

array([4, 5, 7])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [63]:
# your code goes here
np.random.random((3,3,3))

array([[[0.80960781, 0.52111454, 0.50127177],
        [0.36421676, 0.52661197, 0.85547236],
        [0.22134706, 0.86103559, 0.58763412]],

       [[0.46459562, 0.46839449, 0.6137362 ],
        [0.58007828, 0.243775  , 0.31634338],
        [0.30218237, 0.68127287, 0.21299466]],

       [[0.46138751, 0.08146304, 0.2895848 ],
        [0.41913416, 0.68465779, 0.25648676],
        [0.82604789, 0.94329803, 0.33349632]]])

In [61]:
#np.random.random((3,3,3))
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 0.7476872 ,  0.73449614,  0.00651634],
        [-0.01442162,  0.88857638, -0.04906581],
        [-1.29750128,  0.18886417,  0.74336892]],

       [[ 1.12558845,  0.01349802,  0.08996478],
        [ 1.63617229, -0.5594558 ,  0.24241102],
        [ 0.33657003,  0.39304098,  0.6261837 ]],

       [[-0.4280388 , -0.11468152,  0.46928753],
        [-0.30192304,  0.3106024 ,  0.90221915],
        [ 0.45546364,  0.49558344,  0.7086869 ]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [71]:
# your code goes here
x = [1,2,3]
print(x, type(x))

y = np.array(x)
print(y, type(y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [72]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [84]:
# your code goes here
x = np.array([1,2,3])
print(x, id(x))

y= np.copy(x)
print(y, id(y))

[1 2 3] 138754816704208
[1 2 3] 138754817489104


In [82]:
X = np.array([5,2,3], dtype=np.int64)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 138754816701424
[5 2 3] 138754816702192


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [85]:
# your code goes here
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 11)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [87]:
# your code goes here
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1, 11, 2)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [97]:
# your code goes here
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
np.arange(1, 11)[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [99]:
# your code goes here
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.arange(9).reshape(3,3)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [106]:
# your code goes here
z = np.zeros(10)

print("%d bytes" % (z.size * z.itemsize))

80 bytes


In [107]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [109]:
# your code goes here
X = np.array([3,4,5,6,7,8,9,1])

X[0]

np.int64(3)

In [ ]:
X = np.array(['A','B','C','D','E'])

X[0]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [110]:
# your code goes here
X = np.array(['Q','W','E','R','T','Y','U','I','O','P'])
X[-1]

np.str_('P')

In [ ]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [111]:
# your code goes here
X = np.array(['Q','W','E','R','T','Y','U','I','O','P'])
X[0:3]

array(['Q', 'W', 'E'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [113]:
# your code goes here
X = np.array(['Q','W','E','R','T','Y','U','I','O','P'])
X[1:-1]

array(['W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [115]:
# your code goes here
X = np.array(['Q','W','E','R','T','Y','U','I','O','P'])
X[::-1]

array(['P', 'O', 'I', 'U', 'Y', 'T', 'R', 'E', 'W', 'Q'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])

X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [122]:
# your code goes here
X = np.array(['Q','W','E','R','T','Y','U','I','O','P'])
X[::2]

array(['Q', 'E', 'T', 'U', 'O'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [125]:
# your code goes here
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
x[0]

array([1, 2, 3])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [126]:
# your code goes here
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
x[-1]


array([7, 8, 9])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [128]:
# your code goes here
x = np.array([[1, 2, 3, 10],
             [4, 5, 6, 11],
             [7, 8, 9, 12],
              [13,14,15,16]
              ])
x[0,0]

np.int64(1)

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [129]:
# your code goes here
x = np.array([[1, 2, 3, 10],
             [4, 5, 6, 11],
             [7, 8, 9, 12],
              [13,14,15,16]
              ])
x[-1,-1]

np.int64(16)

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [ ]:
# your code goes here


In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [130]:
# your code goes here
x = np.array([
    [1,  2,  3,  10],
    [4,  5,  6,  11],
    [7,  8,  9,  12],
    [13, 14, 15, 16]`
    ])
x[:2,:2]

array([[1, 2],
       [4, 5]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [140]:
# your code goes here
x = np.array([
    [1,  2,  3,  10],
    [4,  5,  6,  11],
    [7,  8,  9,  12],
    [13, 14, 15, 16]
    ])
x[2:,2:]

array([[ 9, 12],
       [15, 16]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [145]:
# your code goes here
y =[1, 2, 3, 4, 5, 6, 7]
np.array(y, np.float64)

array([1., 2., 3., 4., 5., 6., 7.])

In [144]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float64)

array([-5., -3.,  0., 10., 40.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [148]:
# your code goes here
y =np.array([1, 2, 3, 4, 5, 6, 7])
y[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
X = [-5, -3, 0, 10, 40]

X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [151]:
# your code goes here
y =np.array([6, 9, 1, 2, 4, 3, 5, 8, 7])
y.sort()
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
X = [0, 10, -5, 40, -3]

X.sort()
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [156]:
# your code goes here
y =np.array([6, 9, 1, 2, 4, 3, 5, 8, 7])
y[4] = 1
y

array([6, 9, 1, 2, 1, 3, 5, 8, 7])

In [ ]:
X = np.zeros(10)

X[4] = 1
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [157]:
# your code goes here
y = np.array([0, 10, 20, 30, 50])
y[4] = 40
y

array([ 0, 10, 20, 30, 40])

In [ ]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [162]:
# your code goes here
x = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

x[-1] = 1
x


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [168]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1,-1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [170]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [171]:
# your code goes here
x = np.array([-1,2,0,-3,-8,4,-5,6,7,-9])
m = x <=0
m

array([ True, False,  True,  True,  True, False,  True, False, False,
        True])

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [173]:
# your code goes here
x = np.array([-1,2,0,-3,-8,4,-5,6,7,-9])
m = x < 0
x[m]

array([-1, -3, -8, -5, -9])

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [176]:
# your code goes here
x = np.array([-1,2,0,-3,-8,4,-5,6,7,-9])
m = x > 5
x[m]

array([6, 7])

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [185]:
# your code goes here
x = np.array([-1,-2,0,-3,8,-4,-5,6,-7,9])
m = x > x.mean()
x[m]

array([8, 6, 9])

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [187]:
# your code goes here
x = np.array([-1,2,0,-3,-8,4,-5,6,7,-9, 10])
m = (x == 2) | (x == 10)
x[m]

array([ 2, 10])

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [188]:
# your code goes here
x = np.array([-1, 2, 0, -3, -8, 4, -5, 6, 7, -9, 10])
x.all()

np.False_

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [189]:
# your code goes here
x = np.array([-1, 2, 0, -3, -8, 4, -5, 6, 7, -9, 10])
x.any()

np.True_

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [190]:
# your code goes here
x = np.array([2, 5, 8, 9, 2, 3, 5, 7, 4, 6])
x.sum()

np.int64(51)

In [ ]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [191]:
# your code goes here
x = np.array([2, 5, 8, 9, 2, 3, 5, 7, 4, 6])
x.mean()

np.float64(5.1)

In [ ]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [202]:
# your code goes here
x = np.array([
    [1,  3,  2,  5],
    [4,  8,  7,  6],
    [9, 10, 11, 12],
    [16, 14, 13, 15]
    ])

x.sum(axis=0)

array([30, 35, 33, 38])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [203]:
# your code goes here
x = np.array([
    [1,  3,  2,  5],
    [4,  8,  7,  6],
    [9, 10, 11, 12],
    [16, 14, 13, 15]
    ])

x.mean(axis=1)

array([ 2.75,  6.25, 10.5 , 14.5 ])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [204]:
# your code goes here
x = np.array([
    [1,  3,  2,  5],
    [4,  8,  7,  6],
    [9, 10, 11, 12],
    [16, 14, 13, 15]
    ])
x.max()

np.int64(16)

In [ ]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)